version: '3.7'
services:
  
    production-machine-app:
        container_name: productionmachines.app-ge
        image: 'klingelnberg.azurecr.io/gearengine/productionmachines.app:2.1.2'
        restart: always
        ports:
            - '30092:80'
        labels:
            - traefik.http.routers.production-machine-app.rule=PathPrefix(`/web/machines`)
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            ServerConfiguration__ProductionMachineServiceUrl: 'http://productionmachines.service-ge:80'
            BaseUrlConfiguration__BaseUrl: '/web/machines'
    
    
    
networks:
    internal-network:
        driver: bridge
        name: gearengine-network
